# Generated by Django 5.0.1 on 2024-01-07 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetailmodel',
            name='InvoiceModelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.invoicemodel', unique=True),
        ),
    ]
